### ISSUE TITLE
Issue with RVM: Your Ruby version is 2.0.0, but your Gemfile specified 2.3.1

### ISSUE THREAD

**Issue by dbourguignon** [noniq/RuboCop.tmbundle#1]
Hi,

trying to integrate that in my textmate flow, I'm using RVM, and I'm having this error:

Your Ruby version is 2.0.0, but your Gemfile specified 2.3.1

I'm not sure it's specific to your plugin, but for example rspec bundle works correctly

Any idea?

**Comment by noniq** [comment]
RVM is currently not supported. 

My plan is to make this bundle use the new `Executable.find` feature (from the Ruby bundle, see reference above) as soon as it gets merged. Then RVM will be supported, too.

For now, a dirty hack would be to create a binstub in the project directory (`bin/rubocop`) as a simple bash script which initializes RVM and then executes RuboCop (forwarding all command line arguments).

**Comment by dbourguignon** [comment]
OK, that makes sense
I will try the hack and survey future changes then,

thanks

**Comment by dbourguignon** [comment]
Ok it's working with the hack, for the record, I used following script:

bin/rubocop
```bash
#!/usr/bin/env bash

source ~/.rvm/scripts/rvm

rubocop $*
```

**Comment by noniq** [comment]
Since https://github.com/noniq/RuboCop.tmbundle/commit/cad0e5ad99a84ff58583729e1b718725a0bc0c5a this bundle should also work with RVM without any further workarounds or hacks 😉
